 
infer_video:
  min_face_area: 10000
  bbox_threshold: 0.7
  required_images: 16
  validation_threshold: 0.7
  is_anti_spoof: False
  is_vote: False
  distance_mode: 'cosine'
  anti_spoof_threshold: 0.9

identity_person:
  l2_threshold: 1.1
  cosine_threshold: 0.6
  k: 5 
  vote_threshold:  0.8
  distance_mode: 'cosine'